// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataLayer.Entities
{
	[Table("EmailSending")]
	public class EmailSending
	{
		[Column("SendingId"                           )] public long   SendingId         { get; set; } // integer
		[Column("Name"             , CanBeNull = false)] public string Name              { get; set; } = null!; // text(max)
		[Column("Recipients"       , CanBeNull = false)] public string Recipients        { get; set; } = null!; // text(max)
		[Column("MessageTemplateId"                   )] public long   MessageTemplateId { get; set; } // integer
	}
}
