// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataLayer.Entities
{
	[Table("EmailSendingSchedule")]
	public class EmailSendingSchedule
	{
		[Column("EmailSendingScheduleId")] public long     EmailSendingScheduleId { get; set; } // integer
		[Column("ActivationTimePoint"   )] public DateTime ActivationTimePoint    { get; set; } // datetime
		[Column("DeactivationTimePoint" )] public DateTime DeactivationTimePoint  { get; set; } // datetime
		[Column("ActivationInterval"    )] public long     ActivationInterval     { get; set; } // integer
		[Column("EmailSendingId"        )] public long     EmailSendingId         { get; set; } // integer
	}
}
