// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataLayer.Entities
{
	[Table("MeterReadingsPeriodDetails")]
	public class MeterReadingsPeriodDetails
	{
		[Column("MeterReadingsPeriodDetailsId"                   )] public long     MeterReadingsPeriodDetailsId { get; set; } // integer
		[Column("ProvidedServiceName"         , CanBeNull = false)] public string   ProvidedServiceName          { get; set; } = null!; // text(max)
		[Column("ServiceProviderName"         , CanBeNull = false)] public string   ServiceProviderName          { get; set; } = null!; // text(max)
		[Column("MeteringDevice"              , CanBeNull = false)] public string   MeteringDevice               { get; set; } = null!; // text(max)
		[Column("StartTakingReadings"                            )] public DateTime StartTakingReadings          { get; set; } // datetime
		[Column("EndTakingReadings"                              )] public DateTime EndTakingReadings            { get; set; } // datetime
		[Column("UserId"                                         )] public long     UserId                       { get; set; } // integer
	}
}
