// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataLayer.Entities
{
	[Table("PluginAssembly")]
	public class PluginAssembly
	{
		[Column("PluginAssemblyId"                   )] public long     PluginAssemblyId { get; set; } // integer
		[Column("Name"            , CanBeNull = false)] public string   Name             { get; set; } = null!; // text(max)
		[Column("Comment"         , CanBeNull = false)] public string   Comment          { get; set; } = null!; // text(max)
		[Column("Settings"        , CanBeNull = false)] public string   Settings         { get; set; } = null!; // text(max)
		[Column("Data"            , CanBeNull = false)] public byte[]   Data             { get; set; } = null!; // blob
		[Column("CreatedDate"                        )] public DateTime CreatedDate      { get; set; } // datetime
		[Column("UpdatedDate"                        )] public DateTime UpdatedDate      { get; set; } // datetime
	}
}
