// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataLayer.Entities
{
	public partial class StorageDb : DataConnection
	{
		public StorageDb()
		{
			InitDataContext();
		}

		public StorageDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public StorageDb(LinqToDBConnectionOptions<StorageDb> options)
			: base(options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<MeterReadingsPeriodDetails> MeterReadingsPeriodDetails => this.GetTable<MeterReadingsPeriodDetails>();
		public ITable<User>                       User                       => this.GetTable<User>();
		public ITable<Plugin>                     Plugin                     => this.GetTable<Plugin>();
		public ITable<ModelProvider>              ModelProvider              => this.GetTable<ModelProvider>();
		public ITable<MessageTemplate>            MessageTemplate            => this.GetTable<MessageTemplate>();
		public ITable<EmailSending>               EmailSending               => this.GetTable<EmailSending>();
		public ITable<EmailSendingSchedule>       EmailSendingSchedule       => this.GetTable<EmailSendingSchedule>();
	}
}
